version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: le_libros_caribe
      POSTGRES_USER: lecaribe
      POSTGRES_PASSWORD: lecaribe123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://lecaribe:lecaribe123@db/le_libros_caribe
      REDIS_URL: redis://redis:6379
      SECRET_KEY: cambia-esta-clave-en-produccion-debe-ser-larga
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npx ng serve --host 0.0.0.0"
    depends_on:
      - backend

volumes:
  pgdata:
